---
   ### Install Shiny Server
   - name: Get the archive of Shiny Server
     get_url: url=https://download3.rstudio.org/centos5.9/x86_64/shiny-server-1.5.3.838-rh5-x86_64.rpm dest=/tmp/

   - name: Install Shiny Server
     yum: name=/tmp/shiny-server-1.5.3.838-rh5-x86_64.rpm
